RUBY-291 - Driver fails to connect to cluster when a table column type has a quoted name. * Another build.yaml fix

diff --git a/build.yaml b/build.yaml
--- a/build.yaml
+++ b/build.yaml
@@ -39,4 +39,35 @@ build:
 
       # Run the tests; `bundle exec rake test` does all this but seems to be unstable
       # in JRuby9k, so we break down the phases ourselves.
-      bundle exec rake compile && sleep 3 && bundle exec rake rspec && sleep 3 && bundle exec rake integration && sleep 3 && bundle exec rake cucumber
+      RC=0
+      bundle exec rake compile
+      if [ $? -eq 0 ] ; then
+        echo "About to launch unit tests"
+        bundle exec rake rspec
+        if [ $? -eq 0 ] ; then
+          echo "Unit tests completed successfully"
+          bundle exec rake integration
+          if [ $? -eq 0 ] ; then
+            echo "Integration tests completed successfully"
+            bundle exec rake cucumber
+            if [ $? -eq 0 ] ; then
+              echo "Features ran successfully"
+            else
+              echo "Features failed"
+              RC=1
+            fi
+          else
+            echo "Integration tests failed"
+            RC=1
+          fi
+        else
+          echo "Unit tests failed"
+          RC=1
+        fi
+      else
+        echo "Compile failed"
+        RC=1
+      fi
+      if [ $RC -ne 0 ] ; then
+        bin/false
+      fi
