Break apart test phases to hopefully work around jruby9k wackiness

diff --git a/build.yaml b/build.yaml
--- a/build.yaml
+++ b/build.yaml
@@ -38,4 +38,35 @@ build:
       fi
 
       # Run the tests
-      bundle exec rake test
+      RC=0
+      bundle exec rake compile
+      if [ $? -eq 0 ] ; then
+        echo "SANDMAN: about to launch unit tests"
+        bundle exec rake rspec
+        if [ $? -eq 0 ] ; then
+          echo "SANDMAN: unit tests completed successfully"
+          bundle exec rake integration
+          if [ $? -eq 0 ] ; then
+            echo "SANDMAN: integ tests completed successfully"
+            bundle exec rake cucumber
+            if [ $? -eq 0 ] ; then
+              echo "SANDMAN: features ran successfully"
+            else
+              echo "SANDMAN: features failed"
+              RC=1
+            fi
+          else
+            echo "SANDMAN: integ tests failed"
+            RC=1
+          fi
+        else
+          echo "SANDMAN: unit tests failed"
+          RC=1
+        fi
+      else
+        echo "SANDMAN: compile failed"
+        RC=1
+      fi
+      if [ $RC -ne 0 ] ; then
+        bin/false
+      fi
